### ISSUE TITLE
Make the Ovr mode enabled by default and disable the auto-zoom function

### ISSUE THREAD

**Issue by drdrsh** [drdrsh/Jmol-oculusVR#4]

**Comment by Roses-Roses** [comment]
Why did you choose to use steoreo 0, while the default is 5?

**Comment by drdrsh** [comment]
From documentation
"The default rotation is -5 degrees. Sets the number of degrees of clockwise vertical-axis rotation of the RIGHT-hand image relative to the LEFT-hand image"

My understanding is that, in Virtual Reality I am creating 2 images from 2 points of view that are 1 Interpupillary distance apart. My intuition was that the difference between the two images cannot be capture by just simple rotation of the molecule which prompted me to have the two image be identical as that "looked" more closer to what I would see in real life. I am not 100% certain whether my understanding is correct or not though.

**Comment by aalhossary** [comment]
Actually the angle can be 0 only in case the distance is infinity / near to infinity, e.g. when you are looking at the sky.

But for near objects, there should be some rotation, and that’s why one of the components of the accommodation reflex is medial rotation of both eyes.

Any way, we can change and see.

Amr

**Comment by Roses-Roses** [comment]
closed by 1ddda3a69cd26f64f88d03ccf9b8a3002e226714
